import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-fund-administration-nav-fee-audit",
  "engine": "recovery",
  "title": "Fund Administration NAV & Fee Audit",
  "shortTitle": "Fund Administration NAV and Fee Audit",
  "tagline": "Validate fund-administration invoices and NAV-dependent fees across tiers, classes, transactions, and service obligations.",
  "industry": "Investment Fund Operations",
  "buyer": "Asset managers and fund boards",
  "uiPort": 4672,
  "apiPort": 5672,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Fund Administration NAV & Fee Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect administration agreements, NAVs, asset tiers, investor accounts, share classes, transactions, performance data, expenses, fee invoices, and payments in one accountable workflow. Validate fund-administration invoices and NAV-dependent fees across tiers, classes, transactions, and service obligations.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Fund Administration NAV & Fee Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("administration-agreement-library","FAN01","Administration agreement library","Execute administration agreement library using administration agreements, NAVs, asset tiers, investor accounts, share classes, transactions, performance data, expenses, fee invoices, and payments.","Produce a governed administration agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Administrator / Fund","text","Administrator / Fund · Standard Case"],["caseReference","Administration agreement library Reference","text","FAN01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",906250],["supportedAmount","Evidence-Supported Amount","currency",761250],["domainDriver","Fee Basis","select","NAV tier",["NAV tier","Investor count","Transaction volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Administration agreement library case","Fund share-class registry case","Daily monthly NAV ingestion case","Asset tier calculation case","Investor account counts case"]}),
feature("fund-share-class-registry","FAN02","Fund share-class registry","Execute fund share-class registry using administration agreements, NAVs, asset tiers, investor accounts, share classes, transactions, performance data, expenses, fee invoices, and payments.","Produce a governed fund share-class registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Administrator / Fund","text","Administrator / Fund · Standard Case"],["caseReference","Fund share-class registry Reference","text","FAN02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",906250],["supportedAmount","Evidence-Supported Amount","currency",761250],["domainDriver","Fee Basis","select","NAV tier",["NAV tier","Investor count","Transaction volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Administration agreement library case","Fund share-class registry case","Daily monthly NAV ingestion case","Asset tier calculation case","Investor account counts case"]}),
feature("daily-monthly-nav-ingestion","FAN03","Daily monthly NAV ingestion","Execute daily monthly nav ingestion using administration agreements, NAVs, asset tiers, investor accounts, share classes, transactions, performance data, expenses, fee invoices, and payments.","Produce a governed daily monthly nav ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Administrator / Fund","text","Administrator / Fund · Standard Case"],["caseReference","Daily monthly NAV ingestion Reference","text","FAN03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",906250],["supportedAmount","Evidence-Supported Amount","currency",761250],["domainDriver","Fee Basis","select","NAV tier",["NAV tier","Investor count","Transaction volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Administration agreement library case","Fund share-class registry case","Daily monthly NAV ingestion case","Asset tier calculation case","Investor account counts case"]}),
feature("asset-tier-calculation","FAN04","Asset tier calculation","Execute asset tier calculation using administration agreements, NAVs, asset tiers, investor accounts, share classes, transactions, performance data, expenses, fee invoices, and payments.","Produce a governed asset tier calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Administrator / Fund","text","Administrator / Fund · Standard Case"],["caseReference","Asset tier calculation Reference","text","FAN04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",906250],["supportedAmount","Evidence-Supported Amount","currency",761250],["domainDriver","Fee Basis","select","NAV tier",["NAV tier","Investor count","Transaction volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Administration agreement library case","Fund share-class registry case","Daily monthly NAV ingestion case","Asset tier calculation case","Investor account counts case"]}),
feature("investor-account-counts","FAN05","Investor account counts","Execute investor account counts using administration agreements, NAVs, asset tiers, investor accounts, share classes, transactions, performance data, expenses, fee invoices, and payments.","Produce a governed investor account counts decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Administrator / Fund","text","Administrator / Fund · Standard Case"],["caseReference","Investor account counts Reference","text","FAN05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",906250],["supportedAmount","Evidence-Supported Amount","currency",761250],["domainDriver","Fee Basis","select","NAV tier",["NAV tier","Investor count","Transaction volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Administration agreement library case","Fund share-class registry case","Daily monthly NAV ingestion case","Asset tier calculation case","Investor account counts case"]}),
feature("transaction-volume-counts","FAN06","Transaction volume counts","Execute transaction volume counts using administration agreements, NAVs, asset tiers, investor accounts, share classes, transactions, performance data, expenses, fee invoices, and payments.","Produce a governed transaction volume counts decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Administrator / Fund","text","Administrator / Fund · Standard Case"],["caseReference","Transaction volume counts Reference","text","FAN06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",906250],["supportedAmount","Evidence-Supported Amount","currency",761250],["domainDriver","Fee Basis","select","NAV tier",["NAV tier","Investor count","Transaction volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Administration agreement library case","Fund share-class registry case","Daily monthly NAV ingestion case","Asset tier calculation case","Investor account counts case"]}),
feature("base-administration-fee","FAN07","Base administration fee","Execute base administration fee using administration agreements, NAVs, asset tiers, investor accounts, share classes, transactions, performance data, expenses, fee invoices, and payments.","Produce a governed base administration fee decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Administrator / Fund","text","Administrator / Fund · Standard Case"],["caseReference","Base administration fee Reference","text","FAN07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",906250],["supportedAmount","Evidence-Supported Amount","currency",761250],["domainDriver","Fee Basis","select","NAV tier",["NAV tier","Investor count","Transaction volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Administration agreement library case","Fund share-class registry case","Daily monthly NAV ingestion case","Asset tier calculation case","Investor account counts case"]}),
feature("fund-accounting-fee","FAN08","Fund accounting fee","Execute fund accounting fee using administration agreements, NAVs, asset tiers, investor accounts, share classes, transactions, performance data, expenses, fee invoices, and payments.","Produce a governed fund accounting fee decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Administrator / Fund","text","Administrator / Fund · Standard Case"],["caseReference","Fund accounting fee Reference","text","FAN08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",906250],["supportedAmount","Evidence-Supported Amount","currency",761250],["domainDriver","Fee Basis","select","NAV tier",["NAV tier","Investor count","Transaction volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Administration agreement library case","Fund share-class registry case","Daily monthly NAV ingestion case","Asset tier calculation case","Investor account counts case"]}),
feature("transfer-agency-fee","FAN09","Transfer agency fee","Execute transfer agency fee using administration agreements, NAVs, asset tiers, investor accounts, share classes, transactions, performance data, expenses, fee invoices, and payments.","Produce a governed transfer agency fee decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Administrator / Fund","text","Administrator / Fund · Standard Case"],["caseReference","Transfer agency fee Reference","text","FAN09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",906250],["supportedAmount","Evidence-Supported Amount","currency",761250],["domainDriver","Fee Basis","select","NAV tier",["NAV tier","Investor count","Transaction volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Administration agreement library case","Fund share-class registry case","Daily monthly NAV ingestion case","Asset tier calculation case","Investor account counts case"]}),
feature("performance-fee-support","FAN10","Performance fee support","Execute performance fee support using administration agreements, NAVs, asset tiers, investor accounts, share classes, transactions, performance data, expenses, fee invoices, and payments.","Produce a governed performance fee support decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Administrator / Fund","text","Administrator / Fund · Standard Case"],["caseReference","Performance fee support Reference","text","FAN10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",906250],["supportedAmount","Evidence-Supported Amount","currency",761250],["domainDriver","Fee Basis","select","NAV tier",["NAV tier","Investor count","Transaction volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Administration agreement library case","Fund share-class registry case","Daily monthly NAV ingestion case","Asset tier calculation case","Investor account counts case"]}),
feature("service-credit-calculation","FAN11","Service credit calculation","Execute service credit calculation using administration agreements, NAVs, asset tiers, investor accounts, share classes, transactions, performance data, expenses, fee invoices, and payments.","Produce a governed service credit calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Administrator / Fund","text","Administrator / Fund · Standard Case"],["caseReference","Service credit calculation Reference","text","FAN11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",906250],["supportedAmount","Evidence-Supported Amount","currency",761250],["domainDriver","Fee Basis","select","NAV tier",["NAV tier","Investor count","Transaction volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Administration agreement library case","Fund share-class registry case","Daily monthly NAV ingestion case","Asset tier calculation case","Investor account counts case"]}),
feature("invoice-recalculation","FAN12","Invoice recalculation","Execute invoice recalculation using administration agreements, NAVs, asset tiers, investor accounts, share classes, transactions, performance data, expenses, fee invoices, and payments.","Produce a governed invoice recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Administrator / Fund","text","Administrator / Fund · Standard Case"],["caseReference","Invoice recalculation Reference","text","FAN12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",906250],["supportedAmount","Evidence-Supported Amount","currency",761250],["domainDriver","Fee Basis","select","NAV tier",["NAV tier","Investor count","Transaction volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Administration agreement library case","Fund share-class registry case","Daily monthly NAV ingestion case","Asset tier calculation case","Investor account counts case"]}),
feature("administrator-dispute-workflow","FAN13","Administrator dispute workflow","Execute administrator dispute workflow using administration agreements, NAVs, asset tiers, investor accounts, share classes, transactions, performance data, expenses, fee invoices, and payments.","Produce a governed administrator dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Administrator / Fund","text","Administrator / Fund · Standard Case"],["caseReference","Administrator dispute workflow Reference","text","FAN13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",906250],["supportedAmount","Evidence-Supported Amount","currency",761250],["domainDriver","Fee Basis","select","NAV tier",["NAV tier","Investor count","Transaction volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Administration agreement library case","Fund share-class registry case","Daily monthly NAV ingestion case","Asset tier calculation case","Investor account counts case"]}),
feature("payment-credit-reconciliation","FAN14","Payment credit reconciliation","Execute payment credit reconciliation using administration agreements, NAVs, asset tiers, investor accounts, share classes, transactions, performance data, expenses, fee invoices, and payments.","Produce a governed payment credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Administrator / Fund","text","Administrator / Fund · Standard Case"],["caseReference","Payment credit reconciliation Reference","text","FAN14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",906250],["supportedAmount","Evidence-Supported Amount","currency",761250],["domainDriver","Fee Basis","select","NAV tier",["NAV tier","Investor count","Transaction volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Administration agreement library case","Fund share-class registry case","Daily monthly NAV ingestion case","Asset tier calculation case","Investor account counts case"]}),
feature("fund-vendor-analytics","FAN15","Fund vendor analytics","Execute fund vendor analytics using administration agreements, NAVs, asset tiers, investor accounts, share classes, transactions, performance data, expenses, fee invoices, and payments.","Produce a governed fund vendor analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Administrator / Fund","text","Administrator / Fund · Standard Case"],["caseReference","Fund vendor analytics Reference","text","FAN15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",906250],["supportedAmount","Evidence-Supported Amount","currency",761250],["domainDriver","Fee Basis","select","NAV tier",["NAV tier","Investor count","Transaction volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Administration agreement library case","Fund share-class registry case","Daily monthly NAV ingestion case","Asset tier calculation case","Investor account counts case"]})
]);
